import { describe, expect, it } from "vitest";
import { createApp } from "../../index.js"; import { openDatabase } from "../../store/database.js"; import { migrate } from "../../store/migrations.js"; import { createHash } from "node:crypto";
describe("V1 info",()=>{it("is public and reports hosted direct delivery",async()=>{const db=openDatabase(":memory:");migrate(db);const app=createApp({config:{baseUrl:"https://alerts.example.com",relayUrl:"https://relay.critalarm.app",relayContent:"none",listen:":8080",port:8080,dataDir:"/data",behindProxy:false},db,clock:{now:()=>1000},ids:{message:()=>"m",incident:()=>"i",timer:()=>"t"},dispatch:async()=>{}});expect(await (await app.request("/v1/info")).json()).toEqual({name:"critalarm",version:"0.1.0",base_url:"https://alerts.example.com",relay_url:"https://relay.critalarm.app",relay_content:"none",mode:"hosted"});});});

describe("V1 incidents", () => {
  it("acks and closes an owned open incident while rejecting invalid state", async () => {
    const db=openDatabase(":memory:"); migrate(db); db.prepare("INSERT INTO accounts (id,tier,created_at) VALUES ('a','free',1)").run(); db.prepare("INSERT INTO devices (id,account_id,device_token_hash,platform,push_token,last_seen) VALUES ('d','a',?,'ios','x',1)").run(createHash("sha256").update("dv_a").digest("hex"));
    db.prepare("INSERT INTO topics (id,account_id,name,base_url,topic_hash,critical,repeat_interval_s,max_ring_s,desk_timer_s,relay_content,created_at) VALUES ('t','a','prod','https://alerts.example.com','hash',1,30,1800,42,'none',1)").run(); db.prepare("INSERT INTO incidents (id,topic_id,state,opened_at,last_message_at,max_ring_s) VALUES ('inc','t','open',1,1,1800)").run();
    const app=createApp({config:{baseUrl:"https://alerts.example.com",relayUrl:"https://relay.critalarm.app",relayContent:"none",listen:":8080",port:8080,dataDir:"/data",behindProxy:false},db,clock:{now:()=>1000},ids:{message:()=>"m",incident:()=>"new",timer:()=>"timer"},dispatch:async()=>{}}); const headers={Authorization:"Bearer dv_a"};
    expect((await app.request("/v1/incidents",{headers})).status).toBe(200); expect((await app.request("/v1/incidents?limit=bad",{headers})).status).toBe(400); expect((await app.request("/v1/incidents?state=nope",{headers})).status).toBe(400); const ack=await app.request("/v1/incidents/inc/ack",{method:"POST",headers}); expect(await ack.json()).toMatchObject({state:"acked",desk_timer_fires_at:1042}); expect((await app.request("/v1/incidents/inc/ack",{method:"POST",headers})).status).toBe(409); expect((await app.request("/v1/incidents/inc/close",{method:"POST",headers})).status).toBe(200);
  });
});
